### ISSUE TITLE
信号が受信できなかったときにタイムアウトすることがある

### ISSUE THREAD

**Issue by Hiroki-Goto** [open-rdc/rtklib_ros_bridge#2]
RTK測位を行っている時に測位結果が出ないときがあるが，その時ノードがタイムアウトして終了するバグが試走会で何回か見られた

**Comment by Nasupl** [comment]
@Hiroki-Goto 発生時にPythonが吐く例外のログが見たいです

**Comment by Nasupl** [comment]
test
